/**
 * AUTO-GENERATED by scripts/gen_catalog.py — do not edit by hand.
 * Dynamic listing fields shown on the Post Ad form, keyed by subcategory slug.
 * `hasBrand` enables the brand + model dropdowns (see brandData.ts).
 * Extra fields are stored in ads.product_attributes (jsonb).
 */

export type FieldType = 'text' | 'number' | 'select' | 'boolean';
export interface FieldDef {
  key: string;
  label: string;
  type: FieldType;
  options?: string[];
}
export interface CategoryFieldConfig {
  hasBrand: boolean;
  fields: FieldDef[];
}

export const CATEGORY_FIELDS: Record<string, CategoryFieldConfig> = {
  'cars': {
    hasBrand: true,
    fields: [
      { key: 'year', label: 'Year of Manufacture', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'registration_year', label: 'Registration Year', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'mileage', label: 'Mileage (km)', type: 'number' },
      { key: 'fuel_type', label: 'Fuel Type', type: 'select', options: ['Petrol', 'Octane', 'Diesel', 'CNG', 'Hybrid', 'Electric', 'LPG'] },
      { key: 'transmission', label: 'Transmission', type: 'select', options: ['Automatic', 'Manual', 'CVT', 'Tiptronic'] },
      { key: 'engine_cc', label: 'Engine Capacity (cc)', type: 'number' },
      { key: 'body_type', label: 'Body Type', type: 'select', options: ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'Convertible', 'Pickup', 'MPV / Minivan', 'Wagon'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'seats', label: 'Seating Capacity', type: 'select', options: ['2', '4', '5', '7', '8+'] },
      { key: 'registration_area', label: 'Registered City', type: 'text' },
    ],
  },
  'smartphones': {
    hasBrand: true,
    fields: [
      { key: 'ram', label: 'RAM', type: 'select', options: ['1 GB', '2 GB', '3 GB', '4 GB', '6 GB', '8 GB', '12 GB', '16 GB'] },
      { key: 'storage', label: 'Storage', type: 'select', options: ['8 GB', '16 GB', '32 GB', '64 GB', '128 GB', '256 GB', '512 GB', '1 TB'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'network', label: 'Network', type: 'select', options: ['4G', '5G', '3G'] },
      { key: 'sim', label: 'SIM', type: 'select', options: ['Dual SIM', 'Single SIM', 'eSIM'] },
      { key: 'battery', label: 'Battery (mAh)', type: 'number' },
      { key: 'warranty', label: 'Warranty', type: 'select', options: ['No Warranty', 'Official Warranty', 'Shop Warranty', '1 Month', '3 Months', '6 Months', '1 Year'] },
      { key: 'edition', label: 'Region / Edition', type: 'select', options: ['Official', 'Unofficial', 'Global', 'Refurbished'] },
    ],
  },
  'feature-phones': {
    hasBrand: true,
    fields: [
      { key: 'sim', label: 'SIM', type: 'select', options: ['Dual SIM', 'Single SIM'] },
      { key: 'color', label: 'Color', type: 'text' },
    ],
  },
  'tablets': {
    hasBrand: true,
    fields: [
      { key: 'ram', label: 'RAM', type: 'select', options: ['2 GB', '3 GB', '4 GB', '6 GB', '8 GB', '12 GB'] },
      { key: 'storage', label: 'Storage', type: 'select', options: ['16 GB', '32 GB', '64 GB', '128 GB', '256 GB', '512 GB', '1 TB'] },
      { key: 'screen_size', label: 'Screen Size (inch)', type: 'number' },
      { key: 'connectivity', label: 'Connectivity', type: 'select', options: ['WiFi', 'WiFi + Cellular'] },
    ],
  },
  'laptops': {
    hasBrand: true,
    fields: [
      { key: 'processor', label: 'Processor', type: 'select', options: ['Intel Core i3', 'Intel Core i5', 'Intel Core i7', 'Intel Core i9', 'AMD Ryzen 3', 'AMD Ryzen 5', 'AMD Ryzen 7', 'AMD Ryzen 9', 'Apple M1', 'Apple M2', 'Apple M3', 'Other'] },
      { key: 'ram', label: 'RAM', type: 'select', options: ['4 GB', '8 GB', '16 GB', '32 GB', '64 GB'] },
      { key: 'storage', label: 'Storage', type: 'select', options: ['128 GB SSD', '256 GB SSD', '512 GB SSD', '1 TB SSD', '1 TB HDD', '2 TB HDD'] },
      { key: 'gpu', label: 'Graphics', type: 'text' },
      { key: 'screen_size', label: 'Screen Size (inch)', type: 'number' },
    ],
  },
  'desktops': {
    hasBrand: true,
    fields: [
      { key: 'processor', label: 'Processor', type: 'text' },
      { key: 'ram', label: 'RAM', type: 'select', options: ['4 GB', '8 GB', '16 GB', '32 GB', '64 GB'] },
      { key: 'storage', label: 'Storage', type: 'text' },
      { key: 'gpu', label: 'Graphics Card', type: 'text' },
    ],
  },
  'motorcycles': {
    hasBrand: true,
    fields: [
      { key: 'year', label: 'Year', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'engine_cc', label: 'Engine (cc)', type: 'select', options: ['80', '100', '110', '125', '150', '160', '165', '200', '250', '350', '400+'] },
      { key: 'mileage', label: 'Mileage (km)', type: 'number' },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'registration', label: 'Registration', type: 'select', options: ['Registered', 'Unregistered', 'On Test'] },
      { key: 'papers', label: 'Papers', type: 'select', options: ['Up to date', 'Expired'] },
    ],
  },
  'scooters': {
    hasBrand: true,
    fields: [
      { key: 'year', label: 'Year', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'engine_cc', label: 'Engine (cc)', type: 'number' },
      { key: 'mileage', label: 'Mileage (km)', type: 'number' },
      { key: 'color', label: 'Color', type: 'text' },
    ],
  },
  'bicycles': {
    hasBrand: true,
    fields: [
      { key: 'frame_size', label: 'Frame Size', type: 'select', options: ['Kids', 'XS', 'S', 'M', 'L', 'XL'] },
      { key: 'gears', label: 'Gears', type: 'select', options: ['Single Speed', '7 Speed', '21 Speed', '24 Speed', '27 Speed', '30+ Speed'] },
      { key: 'brake_type', label: 'Brake Type', type: 'select', options: ['Rim Brake', 'Disc Brake', 'Hydraulic Disc'] },
      { key: 'wheel_size', label: 'Wheel Size', type: 'select', options: ['12"', '16"', '20"', '24"', '26"', '27.5"', '29"'] },
      { key: 'color', label: 'Color', type: 'text' },
    ],
  },
  'audio': {
    hasBrand: true,
    fields: [
      { key: 'audio_type', label: 'Type', type: 'select', options: ['Bluetooth Speaker', 'Home Theater', 'Soundbar', 'Party Speaker', 'Earbuds', 'Headphones', 'Amplifier'] },
      { key: 'power_output', label: 'Power Output (W)', type: 'number' },
      { key: 'connectivity', label: 'Connectivity', type: 'select', options: ['Bluetooth', 'Wired', 'WiFi', 'Bluetooth + Wired'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'warranty', label: 'Warranty', type: 'select', options: ['No Warranty', '6 Months', '1 Year', '2 Years'] },
    ],
  },
  'tvs': {
    hasBrand: true,
    fields: [
      { key: 'screen_size', label: 'Screen Size (inch)', type: 'select', options: ['24', '32', '40', '43', '50', '55', '65', '75', '85'] },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['HD', 'Full HD', '4K UHD', '8K'] },
      { key: 'panel', label: 'Panel', type: 'select', options: ['LED', 'QLED', 'OLED', 'Neo QLED'] },
      { key: 'smart', label: 'Smart TV', type: 'select', options: ['Smart (Android/Google)', 'Smart (WebOS/Tizen)', 'Non-Smart'] },
      { key: 'warranty', label: 'Warranty', type: 'select', options: ['No Warranty', '1 Year', '2 Years', '3 Years'] },
    ],
  },
  'computer-parts': {
    hasBrand: true,
    fields: [
      { key: 'part_type', label: 'Component Type', type: 'select', options: ['Processor (CPU)', 'Graphics Card (GPU)', 'Motherboard', 'RAM / Memory', 'Storage Drive', 'Power Supply', 'PC Case', 'CPU Cooler', 'Monitor', 'Other'] },
      { key: 'warranty', label: 'Warranty', type: 'select', options: ['No Warranty', 'Shop Warranty', '6 Months', '1 Year', '3 Years', '5 Years'] },
    ],
  },
  'monitors': {
    hasBrand: true,
    fields: [
      { key: 'screen_size', label: 'Screen Size (inch)', type: 'select', options: ['19', '22', '24', '27', '32', '34', '49'] },
      { key: 'resolution', label: 'Resolution', type: 'select', options: ['HD', 'Full HD', '2K QHD', '4K UHD'] },
      { key: 'refresh_rate', label: 'Refresh Rate', type: 'select', options: ['60Hz', '75Hz', '100Hz', '144Hz', '165Hz', '240Hz'] },
      { key: 'panel', label: 'Panel', type: 'select', options: ['IPS', 'VA', 'TN', 'OLED'] },
    ],
  },
  'apartments-rent': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'dogs': {
    hasBrand: false,
    fields: [
      { key: 'breed', label: 'Breed', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { key: 'vaccinated', label: 'Vaccinated', type: 'select', options: ['Yes', 'No', 'Partially'] },
    ],
  },
  'cats': {
    hasBrand: false,
    fields: [
      { key: 'breed', label: 'Breed', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { key: 'vaccinated', label: 'Vaccinated', type: 'select', options: ['Yes', 'No', 'Partially'] },
    ],
  },
  'apartments-sale': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'houses-rent': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'houses-sale': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'commercial': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'rooms': {
    hasBrand: false,
    fields: [
      { key: 'bedrooms', label: 'Bedrooms', type: 'select', options: ['1', '2', '3', '4', '5+'] },
      { key: 'bathrooms', label: 'Bathrooms', type: 'select', options: ['1', '2', '3', '4+'] },
      { key: 'size_sqft', label: 'Size (sqft)', type: 'number' },
      { key: 'floor', label: 'Floor', type: 'text' },
      { key: 'furnishing', label: 'Furnishing', type: 'select', options: ['Furnished', 'Semi-Furnished', 'Unfurnished'] },
      { key: 'facing', label: 'Facing', type: 'select', options: ['South', 'North', 'East', 'West'] },
    ],
  },
  'birds': {
    hasBrand: false,
    fields: [
      { key: 'breed', label: 'Breed', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { key: 'vaccinated', label: 'Vaccinated', type: 'select', options: ['Yes', 'No', 'Partially'] },
    ],
  },
  'fish': {
    hasBrand: false,
    fields: [
      { key: 'breed', label: 'Breed', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { key: 'vaccinated', label: 'Vaccinated', type: 'select', options: ['Yes', 'No', 'Partially'] },
    ],
  },
  'livestock': {
    hasBrand: false,
    fields: [
      { key: 'breed', label: 'Breed', type: 'text' },
      { key: 'age', label: 'Age', type: 'text' },
      { key: 'gender', label: 'Gender', type: 'select', options: ['Male', 'Female'] },
      { key: 'vaccinated', label: 'Vaccinated', type: 'select', options: ['Yes', 'No', 'Partially'] },
    ],
  },
  'electric-cars': {
    hasBrand: true,
    fields: [
      { key: 'year', label: 'Year of Manufacture', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'registration_year', label: 'Registration Year', type: 'select', options: ['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008', '2007', '2006', '2005', '2004', '2003', '2002', '2001', '2000', '1999', '1998', '1997', '1996', '1995'] },
      { key: 'mileage', label: 'Mileage (km)', type: 'number' },
      { key: 'fuel_type', label: 'Fuel Type', type: 'select', options: ['Petrol', 'Octane', 'Diesel', 'CNG', 'Hybrid', 'Electric', 'LPG'] },
      { key: 'transmission', label: 'Transmission', type: 'select', options: ['Automatic', 'Manual', 'CVT', 'Tiptronic'] },
      { key: 'engine_cc', label: 'Engine Capacity (cc)', type: 'number' },
      { key: 'body_type', label: 'Body Type', type: 'select', options: ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'Convertible', 'Pickup', 'MPV / Minivan', 'Wagon'] },
      { key: 'color', label: 'Color', type: 'text' },
      { key: 'seats', label: 'Seating Capacity', type: 'select', options: ['2', '4', '5', '7', '8+'] },
      { key: 'registration_area', label: 'Registered City', type: 'text' },
    ],
  },
};

export function getCategoryFields(subcategorySlug?: string | null): CategoryFieldConfig | null {
  if (!subcategorySlug) return null;
  return CATEGORY_FIELDS[subcategorySlug] || null;
}
