/**
 * AUTO-GENERATED by scripts/gen_catalog.py — do not edit by hand.
 * Full marketplace taxonomy: categories -> subcategories -> item types.
 * 'itemTypes' answers "what type of item is this?" (e.g. Pets -> Dog/Cat/Bird).
 */

export interface TaxonomySubcategory {
  slug: string;
  name: string;
  itemTypes: string[];
}
export interface TaxonomyCategory {
  slug: string;
  name: string;
  icon: string;
  color: string;
  description: string;
  subcategories: TaxonomySubcategory[];
}

export const TAXONOMY: TaxonomyCategory[] = [
  {
    slug: 'electronics', name: 'Electronics', icon: 'Smartphone',
    color: 'text-blue-600 bg-blue-50 dark:bg-blue-950/40',
    description: 'Phones, computers, gadgets and accessories',
    subcategories: [
      { slug: 'smartphones', name: 'Smartphones', itemTypes: ['Android Phone', 'iPhone', 'Foldable Phone', 'Gaming Phone', 'Refurbished Phone'] },
      { slug: 'feature-phones', name: 'Feature Phones', itemTypes: ['Button Phone', 'Dual SIM', 'Senior Phone'] },
      { slug: 'tablets', name: 'Tablets', itemTypes: ['Android Tablet', 'iPad', 'Drawing Tablet', 'Kids Tablet'] },
      { slug: 'laptops', name: 'Laptops & Notebooks', itemTypes: ['Gaming Laptop', 'Ultrabook', 'Business Laptop', '2-in-1 Convertible', 'MacBook', 'Chromebook'] },
      { slug: 'desktops', name: 'Desktop Computers', itemTypes: ['Gaming PC', 'All-in-One', 'Workstation', 'Mini PC', 'Branded Desktop'] },
      { slug: 'computer-parts', name: 'Computer Components', itemTypes: ['Processor (CPU)', 'Graphics Card (GPU)', 'Motherboard', 'RAM / Memory', 'Storage Drive', 'Power Supply', 'PC Case', 'CPU Cooler'] },
      { slug: 'processors', name: 'Processors (CPU)', itemTypes: ['Intel', 'AMD'] },
      { slug: 'graphics-cards', name: 'Graphics Cards (GPU)', itemTypes: ['NVIDIA', 'AMD Radeon'] },
      { slug: 'motherboards', name: 'Motherboards', itemTypes: ['Intel Socket', 'AMD Socket', 'Micro-ATX', 'ATX', 'Mini-ITX'] },
      { slug: 'ram-memory', name: 'RAM / Memory', itemTypes: ['DDR4', 'DDR5', 'Laptop RAM (SODIMM)'] },
      { slug: 'storage-drives', name: 'Storage Drives', itemTypes: ['SSD (SATA)', 'SSD (NVMe)', 'HDD', 'External Drive'] },
      { slug: 'monitors', name: 'Monitors', itemTypes: ['Gaming Monitor', '4K Monitor', 'Curved Monitor', 'Office Monitor'] },
      { slug: 'printers', name: 'Printers & Scanners', itemTypes: ['Inkjet', 'LaserJet', 'All-in-One', 'Photo Printer', 'Scanner'] },
      { slug: 'cameras', name: 'Cameras & Photography', itemTypes: ['DSLR', 'Mirrorless', 'Point & Shoot', 'Action Camera', 'CCTV', 'Drone', 'Lens', 'Camera Accessories'] },
      { slug: 'tvs', name: 'TVs & Displays', itemTypes: ['Smart TV', 'LED TV', 'QLED TV', 'OLED TV', 'Android TV', 'Projector'] },
      { slug: 'audio', name: 'Audio & Speakers', itemTypes: ['Bluetooth Speaker', 'Home Theater', 'Soundbar', 'Party Speaker', 'Earbuds', 'Headphones', 'Microphone', 'Amplifier'] },
      { slug: 'gaming', name: 'Gaming Consoles', itemTypes: ['PlayStation', 'Xbox', 'Nintendo', 'Handheld Console', 'Game Accessories', 'Video Games'] },
      { slug: 'networking', name: 'Networking & WiFi', itemTypes: ['Router', 'WiFi Extender', 'Switch', 'ONU / Modem', 'Access Point'] },
      { slug: 'wearables', name: 'Smart Watches & Wearables', itemTypes: ['Smartwatch', 'Fitness Band', 'Smart Ring'] },
      { slug: 'accessories', name: 'Accessories & Cables', itemTypes: ['Charger', 'Power Bank', 'Cable', 'Mouse', 'Keyboard', 'Webcam', 'Cover / Case'] },
    ],
  },
  {
    slug: 'vehicles', name: 'Vehicles', icon: 'Car',
    color: 'text-red-600 bg-red-50 dark:bg-red-950/40',
    description: 'Cars, bikes, and everything on wheels',
    subcategories: [
      { slug: 'cars', name: 'Cars', itemTypes: ['Sedan', 'SUV', 'Hatchback', 'Coupe', 'Convertible', 'Pickup', 'MPV / Minivan', 'Electric Car', 'Hybrid'] },
      { slug: 'motorcycles', name: 'Motorcycles', itemTypes: ['Commuter', 'Sports Bike', 'Cruiser', 'Cafe Racer', 'Off-road / Dirt', 'Electric Motorcycle'] },
      { slug: 'scooters', name: 'Scooters', itemTypes: ['Petrol Scooter', 'Electric Scooter', 'Moped'] },
      { slug: 'bicycles', name: 'Bicycles', itemTypes: ['Mountain Bike', 'Road Bike', 'Hybrid Bike', 'BMX', 'Folding Bike', 'Kids Bicycle', 'Electric Bicycle'] },
      { slug: 'three-wheelers', name: 'Three Wheelers', itemTypes: ['CNG Auto-rickshaw', 'Easy Bike', 'Battery Rickshaw', 'Loader'] },
      { slug: 'trucks', name: 'Trucks & Commercial', itemTypes: ['Pickup Truck', 'Covered Van', 'Truck', 'Bus / Minibus', 'Tractor'] },
      { slug: 'auto-parts', name: 'Auto Parts & Accessories', itemTypes: ['Tyres & Wheels', 'Batteries', 'Engine Parts', 'Body Parts', 'Car Audio', 'Lights', 'Interior', 'Oils & Fluids'] },
      { slug: 'boats', name: 'Boats & Watercraft', itemTypes: ['Speed Boat', 'Fishing Boat', 'Engine Boat', 'Trawler'] },
      { slug: 'vehicle-services', name: 'Vehicle Services', itemTypes: ['Rental', 'Insurance', 'Number Plate', 'Registration'] },
    ],
  },
  {
    slug: 'real-estate', name: 'Real Estate', icon: 'Home',
    color: 'text-emerald-600 bg-emerald-50 dark:bg-emerald-950/40',
    description: 'Property to rent, buy and sell',
    subcategories: [
      { slug: 'apartments-rent', name: 'Apartments for Rent', itemTypes: ['Family Apartment', 'Bachelor', 'Studio', 'Duplex', 'Furnished'] },
      { slug: 'apartments-sale', name: 'Apartments for Sale', itemTypes: ['Ready Flat', 'Under Construction', 'Duplex', 'Penthouse'] },
      { slug: 'houses-rent', name: 'Houses for Rent', itemTypes: ['Single House', 'Duplex House', 'Tin-shed'] },
      { slug: 'houses-sale', name: 'Houses for Sale', itemTypes: ['Independent House', 'Duplex', 'Building'] },
      { slug: 'land', name: 'Land & Plots', itemTypes: ['Residential Plot', 'Commercial Plot', 'Agricultural Land', 'Industrial Land'] },
      { slug: 'commercial', name: 'Commercial Property', itemTypes: ['Office Space', 'Shop / Showroom', 'Warehouse', 'Factory', 'Restaurant Space'] },
      { slug: 'rooms', name: 'Rooms & Sublets', itemTypes: ['Single Room', 'Shared Room', 'Sublet', 'Hostel Seat', 'Mess Seat'] },
      { slug: 'garages', name: 'Garages & Parking', itemTypes: ['Car Parking', 'Garage'] },
      { slug: 'vacation', name: 'Vacation Rentals', itemTypes: ['Resort', 'Cottage', 'Guest House'] },
    ],
  },
  {
    slug: 'mobiles-tablets', name: 'Mobiles & Tablets', icon: 'Smartphone',
    color: 'text-sky-600 bg-sky-50 dark:bg-sky-950/40',
    description: 'Phones, tablets and mobile accessories',
    subcategories: [
      { slug: 'smartphones', name: 'Smartphones', itemTypes: ['Android Phone', 'iPhone', 'Foldable Phone', 'Gaming Phone', 'Refurbished Phone'] },
      { slug: 'feature-phones', name: 'Feature Phones', itemTypes: ['Button Phone', 'Dual SIM', 'Senior Phone'] },
      { slug: 'tablets', name: 'Tablets', itemTypes: ['Android Tablet', 'iPad', 'Kids Tablet'] },
      { slug: 'mobile-accessories', name: 'Mobile Accessories', itemTypes: ['Charger', 'Power Bank', 'Cover / Case', 'Screen Protector', 'Cable', 'Holder', 'Selfie Stick'] },
      { slug: 'sim-cards', name: 'SIM Cards & Numbers', itemTypes: ['VIP Number', 'Prepaid', 'Postpaid'] },
      { slug: 'wearables', name: 'Smart Watches', itemTypes: ['Smartwatch', 'Fitness Band', 'Kids Watch'] },
    ],
  },
  {
    slug: 'jobs', name: 'Jobs', icon: 'Briefcase',
    color: 'text-indigo-600 bg-indigo-50 dark:bg-indigo-950/40',
    description: 'Find work and hire talent',
    subcategories: [
      { slug: 'it-software', name: 'IT & Software', itemTypes: ['Full-time', 'Part-time', 'Contract', 'Remote', 'Internship'] },
      { slug: 'sales-marketing', name: 'Sales & Marketing', itemTypes: ['Full-time', 'Part-time', 'Commission', 'Remote'] },
      { slug: 'accounting', name: 'Accounting & Finance', itemTypes: ['Full-time', 'Part-time', 'Contract'] },
      { slug: 'teaching', name: 'Teaching & Education', itemTypes: ['School Teacher', 'Private Tutor', 'Coaching', 'Online Tutor'] },
      { slug: 'drivers', name: 'Driver & Transport', itemTypes: ['Car Driver', 'Truck Driver', 'Delivery', 'Rider'] },
      { slug: 'garments', name: 'Garments & Factory', itemTypes: ['Operator', 'Supervisor', 'Quality Control', 'Merchandiser'] },
      { slug: 'healthcare', name: 'Healthcare & Medical', itemTypes: ['Doctor', 'Nurse', 'Pharmacist', 'Technician'] },
      { slug: 'hospitality', name: 'Hotel & Restaurant', itemTypes: ['Chef', 'Waiter', 'Manager', 'Housekeeping'] },
      { slug: 'domestic', name: 'Domestic Help', itemTypes: ['Maid', 'Cook', 'Caregiver', 'Security Guard'] },
      { slug: 'part-time', name: 'Part-Time & Freelance', itemTypes: ['Freelance', 'Internship', 'Day Labour'] },
      { slug: 'govt', name: 'Government Jobs', itemTypes: ['Govt Circular', 'Bank Job', 'Defence'] },
    ],
  },
  {
    slug: 'services', name: 'Services', icon: 'Wrench',
    color: 'text-orange-600 bg-orange-50 dark:bg-orange-950/40',
    description: 'Hire local professionals and businesses',
    subcategories: [
      { slug: 'electronics-repair', name: 'Electronics Repair', itemTypes: ['Mobile Repair', 'Laptop Repair', 'TV Repair', 'AC / Fridge Repair'] },
      { slug: 'home-services', name: 'Home Services', itemTypes: ['Cleaning', 'Pest Control', 'Shifting / Moving', 'Interior Design'] },
      { slug: 'electrician', name: 'Electrician', itemTypes: ['Wiring', 'Installation', 'Repair'] },
      { slug: 'plumber', name: 'Plumber', itemTypes: ['Repair', 'Installation', 'Fittings'] },
      { slug: 'construction', name: 'Construction & Renovation', itemTypes: ['Civil Work', 'Painting', 'Tiles', 'Carpentry', 'Welding'] },
      { slug: 'events', name: 'Events & Catering', itemTypes: ['Catering', 'Event Planning', 'Photography', 'Decoration', 'Sound & Lighting'] },
      { slug: 'beauty', name: 'Beauty & Wellness', itemTypes: ['Salon', 'Spa', 'Bridal Makeup', 'Parlour at Home'] },
      { slug: 'education-services', name: 'Tutoring & Coaching', itemTypes: ['Home Tutor', 'Coaching Center', 'Language', 'Music Lessons'] },
      { slug: 'professional', name: 'Professional Services', itemTypes: ['Legal', 'Accounting', 'Consulting', 'Translation', 'Web / IT'] },
      { slug: 'travel-services', name: 'Travel & Transport', itemTypes: ['Rent-a-car', 'Tour Package', 'Ticketing', 'Courier'] },
    ],
  },
  {
    slug: 'fashion', name: 'Fashion & Beauty', icon: 'Shirt',
    color: 'text-pink-600 bg-pink-50 dark:bg-pink-950/40',
    description: 'Clothing, footwear, accessories and cosmetics',
    subcategories: [
      { slug: 'mens-clothing', name: 'Men\'s Clothing', itemTypes: ['Shirt', 'T-Shirt', 'Panjabi', 'Pant', 'Suit', 'Jacket', 'Traditional'] },
      { slug: 'womens-clothing', name: 'Women\'s Clothing', itemTypes: ['Saree', 'Salwar Kameez', 'Kurti', 'Dress', 'Abaya / Borka', 'Lehenga'] },
      { slug: 'kids-clothing', name: 'Kids\' Clothing', itemTypes: ['Boys', 'Girls', 'Baby', 'Party Wear'] },
      { slug: 'footwear', name: 'Footwear', itemTypes: ['Sneakers', 'Formal Shoes', 'Sandals', 'Heels', 'Boots', 'Sports Shoes'] },
      { slug: 'watches', name: 'Watches', itemTypes: ['Analog', 'Digital', 'Smart', 'Luxury'] },
      { slug: 'bags', name: 'Bags & Luggage', itemTypes: ['Handbag', 'Backpack', 'Travel Bag', 'Wallet', 'Ladies Purse'] },
      { slug: 'jewellery', name: 'Jewellery', itemTypes: ['Gold', 'Silver', 'Imitation', 'Diamond', 'Wedding'] },
      { slug: 'cosmetics', name: 'Cosmetics & Makeup', itemTypes: ['Skincare', 'Makeup', 'Fragrance', 'Haircare'] },
      { slug: 'eyewear', name: 'Eyewear', itemTypes: ['Sunglasses', 'Prescription', 'Frames'] },
    ],
  },
  {
    slug: 'home-living', name: 'Home & Living', icon: 'Sofa',
    color: 'text-amber-600 bg-amber-50 dark:bg-amber-950/40',
    description: 'Furniture, appliances and home essentials',
    subcategories: [
      { slug: 'furniture', name: 'Furniture', itemTypes: ['Sofa', 'Bed', 'Wardrobe', 'Dining Table', 'Chair', 'Study Table', 'Showcase', 'Office Furniture'] },
      { slug: 'home-appliances', name: 'Home Appliances', itemTypes: ['Refrigerator', 'Washing Machine', 'Microwave Oven', 'Rice Cooker', 'Blender', 'Iron', 'Water Purifier'] },
      { slug: 'ac-cooling', name: 'AC & Cooling', itemTypes: ['Split AC', 'Window AC', 'Portable AC', 'Air Cooler', 'Ceiling Fan', 'Table Fan'] },
      { slug: 'kitchen', name: 'Kitchenware', itemTypes: ['Cookware', 'Dinnerware', 'Gas Stove', 'Pressure Cooker', 'Utensils'] },
      { slug: 'home-decor', name: 'Home Decor', itemTypes: ['Wall Art', 'Curtains', 'Carpet', 'Lighting', 'Clock', 'Vase'] },
      { slug: 'bedding', name: 'Bedding & Bath', itemTypes: ['Mattress', 'Bedsheet', 'Pillow', 'Blanket', 'Towel'] },
      { slug: 'tools', name: 'Tools & Hardware', itemTypes: ['Power Tools', 'Hand Tools', 'Plumbing', 'Electrical', 'Paint'] },
      { slug: 'garden', name: 'Garden & Outdoor', itemTypes: ['Plants', 'Seeds', 'Garden Tools', 'Outdoor Furniture'] },
    ],
  },
  {
    slug: 'sports-fitness', name: 'Sports & Fitness', icon: 'Dumbbell',
    color: 'text-lime-600 bg-lime-50 dark:bg-lime-950/40',
    description: 'Gym, sports gear and outdoor equipment',
    subcategories: [
      { slug: 'gym-equipment', name: 'Gym & Fitness', itemTypes: ['Treadmill', 'Dumbbell', 'Exercise Bike', 'Home Gym', 'Yoga Mat', 'Bench'] },
      { slug: 'cricket', name: 'Cricket', itemTypes: ['Bat', 'Ball', 'Pads', 'Gloves', 'Kit'] },
      { slug: 'football', name: 'Football', itemTypes: ['Ball', 'Boots', 'Jersey', 'Gloves'] },
      { slug: 'cycling-sports', name: 'Cycling', itemTypes: ['Bicycle', 'Helmet', 'Accessories'] },
      { slug: 'outdoor', name: 'Outdoor & Camping', itemTypes: ['Tent', 'Sleeping Bag', 'Backpack', 'Trekking Gear'] },
      { slug: 'indoor-games', name: 'Indoor Games', itemTypes: ['Carrom', 'Chess', 'Table Tennis', 'Board Games'] },
      { slug: 'water-sports', name: 'Water Sports', itemTypes: ['Swimming', 'Fishing', 'Diving'] },
    ],
  },
  {
    slug: 'books-education', name: 'Books & Education', icon: 'BookOpen',
    color: 'text-cyan-600 bg-cyan-50 dark:bg-cyan-950/40',
    description: 'Books, courses and stationery',
    subcategories: [
      { slug: 'academic', name: 'Academic Books', itemTypes: ['School', 'College', 'University', 'Admission', 'Guide'] },
      { slug: 'fiction', name: 'Fiction & Literature', itemTypes: ['Novel', 'Story', 'Poetry'] },
      { slug: 'religious', name: 'Religious Books', itemTypes: ['Islamic', 'Hindu', 'Christian', 'Buddhist'] },
      { slug: 'stationery', name: 'Stationery', itemTypes: ['Pen & Pencil', 'Notebook', 'Art Supplies', 'Office Supplies'] },
      { slug: 'courses', name: 'Courses & Training', itemTypes: ['Online Course', 'Skill Training', 'Language Course'] },
      { slug: 'magazines', name: 'Magazines & Comics', itemTypes: ['Magazine', 'Comics', 'Newspaper'] },
    ],
  },
  {
    slug: 'baby-kids', name: 'Baby & Kids', icon: 'Baby',
    color: 'text-rose-600 bg-rose-50 dark:bg-rose-950/40',
    description: 'Everything for babies and children',
    subcategories: [
      { slug: 'baby-gear', name: 'Baby Gear', itemTypes: ['Stroller', 'Car Seat', 'Walker', 'High Chair', 'Carrier'] },
      { slug: 'toys', name: 'Toys & Games', itemTypes: ['Educational', 'Remote Control', 'Soft Toys', 'Puzzles', 'Action Figures', 'Dolls'] },
      { slug: 'baby-clothing', name: 'Baby Clothing', itemTypes: ['Newborn', 'Boys', 'Girls'] },
      { slug: 'feeding', name: 'Feeding & Nursing', itemTypes: ['Bottle', 'Breast Pump', 'Sterilizer'] },
      { slug: 'diapers', name: 'Diapers & Care', itemTypes: ['Diapers', 'Wipes', 'Skincare'] },
      { slug: 'kids-furniture', name: 'Kids Furniture', itemTypes: ['Baby Bed', 'Study Table', 'Toy Storage'] },
    ],
  },
  {
    slug: 'pets-animals', name: 'Pets & Animals', icon: 'PawPrint',
    color: 'text-teal-600 bg-teal-50 dark:bg-teal-950/40',
    description: 'Pets, livestock and pet supplies',
    subcategories: [
      { slug: 'dogs', name: 'Dogs', itemTypes: ['German Shepherd', 'Labrador', 'Pomeranian', 'Husky', 'Local Breed', 'Puppy'] },
      { slug: 'cats', name: 'Cats', itemTypes: ['Persian', 'Traditional', 'Ragdoll', 'Local Breed', 'Kitten'] },
      { slug: 'birds', name: 'Birds', itemTypes: ['Budgerigar', 'Cockatiel', 'Love Bird', 'Pigeon', 'Parrot', 'Finch', 'Java'] },
      { slug: 'fish', name: 'Fish & Aquarium', itemTypes: ['Goldfish', 'Guppy', 'Koi', 'Aquarium', 'Aquarium Accessories'] },
      { slug: 'livestock', name: 'Livestock & Farm', itemTypes: ['Cow', 'Goat', 'Sheep', 'Buffalo', 'Chicken', 'Duck'] },
      { slug: 'pet-food', name: 'Pet Food', itemTypes: ['Dog Food', 'Cat Food', 'Bird Food', 'Fish Food'] },
      { slug: 'pet-accessories', name: 'Pet Accessories', itemTypes: ['Cage', 'Leash', 'Bed', 'Toys', 'Grooming'] },
    ],
  },
  {
    slug: 'agriculture', name: 'Agriculture', icon: 'Sprout',
    color: 'text-green-700 bg-green-50 dark:bg-green-950/40',
    description: 'Farming, crops and machinery',
    subcategories: [
      { slug: 'crops-seeds', name: 'Crops & Seeds', itemTypes: ['Rice', 'Vegetables', 'Fruits', 'Seeds', 'Saplings'] },
      { slug: 'farm-machinery', name: 'Farm Machinery', itemTypes: ['Tractor', 'Power Tiller', 'Harvester', 'Pump', 'Thresher'] },
      { slug: 'fertilizer', name: 'Fertilizer & Pesticide', itemTypes: ['Fertilizer', 'Pesticide', 'Organic'] },
      { slug: 'poultry', name: 'Poultry & Dairy', itemTypes: ['Poultry Equipment', 'Dairy Equipment', 'Feed'] },
      { slug: 'agri-tools', name: 'Agri Tools', itemTypes: ['Hand Tools', 'Irrigation', 'Sprayer'] },
    ],
  },
  {
    slug: 'food-catering', name: 'Food & Catering', icon: 'UtensilsCrossed',
    color: 'text-orange-700 bg-orange-50 dark:bg-orange-950/40',
    description: 'Homemade food, groceries and catering',
    subcategories: [
      { slug: 'homemade', name: 'Homemade Food', itemTypes: ['Cakes', 'Snacks', 'Meals', 'Pickle', 'Sweets'] },
      { slug: 'groceries', name: 'Groceries', itemTypes: ['Rice & Grains', 'Oil', 'Spices', 'Dry Food'] },
      { slug: 'beverages', name: 'Beverages', itemTypes: ['Tea', 'Coffee', 'Juice', 'Soft Drinks'] },
      { slug: 'organic-food', name: 'Organic & Special', itemTypes: ['Honey', 'Ghee', 'Dates', 'Organic'] },
      { slug: 'catering', name: 'Catering & Restaurant', itemTypes: ['Catering Service', 'Cloud Kitchen'] },
    ],
  },
  {
    slug: 'health-medical', name: 'Health & Medical', icon: 'HeartPulse',
    color: 'text-red-700 bg-red-50 dark:bg-red-950/40',
    description: 'Medical equipment, supplements and care',
    subcategories: [
      { slug: 'medical-equipment', name: 'Medical Equipment', itemTypes: ['Wheelchair', 'Oxygen Concentrator', 'BP Machine', 'Nebulizer', 'Thermometer', 'Hospital Bed'] },
      { slug: 'supplements', name: 'Supplements & Vitamins', itemTypes: ['Protein', 'Vitamins', 'Herbal'] },
      { slug: 'personal-care', name: 'Personal Care', itemTypes: ['Skincare', 'Hygiene', 'Massager'] },
      { slug: 'fitness-health', name: 'Fitness & Health', itemTypes: ['Weighing Scale', 'Fitness Tracker'] },
    ],
  },
  {
    slug: 'business-industrial', name: 'Business & Industrial', icon: 'Factory',
    color: 'text-slate-600 bg-slate-50 dark:bg-slate-900/40',
    description: 'Machinery, equipment and B2B supplies',
    subcategories: [
      { slug: 'machinery', name: 'Industrial Machinery', itemTypes: ['Generator', 'Compressor', 'Lathe', 'CNC', 'Packaging'] },
      { slug: 'office-equipment', name: 'Office Equipment', itemTypes: ['Photocopier', 'POS Machine', 'Projector', 'Shredder'] },
      { slug: 'restaurant-equipment', name: 'Restaurant Equipment', itemTypes: ['Oven', 'Fryer', 'Freezer', 'Display Counter'] },
      { slug: 'construction-material', name: 'Construction Materials', itemTypes: ['Rod', 'Cement', 'Brick', 'Tiles', 'Sand'] },
      { slug: 'safety', name: 'Safety & Security', itemTypes: ['CCTV', 'Fire Safety', 'Access Control', 'Safety Gear'] },
      { slug: 'wholesale', name: 'Wholesale & Bulk', itemTypes: ['Bulk Stock', 'Liquidation'] },
    ],
  },
  {
    slug: 'hobbies-collectibles', name: 'Hobbies & Collectibles', icon: 'Palette',
    color: 'text-purple-600 bg-purple-50 dark:bg-purple-950/40',
    description: 'Musical instruments, art and collectibles',
    subcategories: [
      { slug: 'musical-instruments', name: 'Musical Instruments', itemTypes: ['Guitar', 'Keyboard', 'Drums', 'Harmonium', 'Tabla', 'Violin', 'Flute'] },
      { slug: 'art-craft', name: 'Art & Craft', itemTypes: ['Painting', 'Handicraft', 'Sculpture', 'Craft Supplies'] },
      { slug: 'antiques', name: 'Antiques & Collectibles', itemTypes: ['Coins', 'Stamps', 'Vintage', 'Artifacts'] },
      { slug: 'cameras-hobby', name: 'Cameras & Drones', itemTypes: ['Camera', 'Drone', 'Gimbal'] },
      { slug: 'gaming-hobby', name: 'Gaming & Cards', itemTypes: ['Trading Cards', 'Board Games', 'Models'] },
    ],
  },
];

export function getItemTypes(categorySlug?: string | null, subcategorySlug?: string | null): string[] {
  const cat = TAXONOMY.find((c) => c.slug === categorySlug);
  if (!cat) return [];
  if (subcategorySlug) {
    const sc = cat.subcategories.find((s) => s.slug === subcategorySlug);
    if (sc) return sc.itemTypes;
  }
  return [];
}

export const TOTAL_CATEGORIES = TAXONOMY.length;
export const TOTAL_SUBCATEGORIES = TAXONOMY.reduce((n, c) => n + c.subcategories.length, 0);
