-- DEPRECATED — do not run this file.
-- This is the old, unnumbered version. The maintained, idempotent
-- schema now lives in the ordered migration set. Run the numbered
-- files 01..16 in order instead (see supabase/README.md).
--
-- Equivalent maintained file: 14_schema_v14_admin_portal.sql
